"use strict";

/*==================================================

    PROJECT SHIZ
    A.R.C.S.

    Version 3.4.0 Modular Edition

    js/main.js

==================================================*/




/*==================================================
    CREATOR CARD
==================================================*/

function updateCreatorCard(entry, idText, confidence) {
    if (!DOM.creatorPanel) return;

    DOM.creatorResultTitle.textContent = entry.title;

    fitResultTitle(DOM.creatorResultTitle, {
        maxSize: 56,
        minSize: 24,
        maxLines: 3
    });

    DOM.creatorOperator.textContent = App.settings.operatorName;
    DOM.creatorResultId.textContent = idText;
    DOM.creatorConfidence.textContent = `${confidence}%`;
}

function resetCreatorCard() {
    if (!DOM.creatorPanel) return;

    DOM.creatorResultTitle.textContent = "---";
    resetTitleFit(DOM.creatorResultTitle);

    DOM.creatorOperator.textContent = "---";
    DOM.creatorResultId.textContent = "----";
    DOM.creatorConfidence.textContent = "--.--%";
}

async function openCreatorPanel() {
    if (!DOM.creatorPanel) return;

    if (!App.selectedEntry) {
        Terminal.warn("No result data available.");
        setSystemMessage("NO RESULT");
        return;
    }

    Terminal.system("Accessing creator module...");
    setSystemMessage("CREATOR MODULE");

    await sleep(260);

    DOM.creatorPanel.classList.add("open");

    Terminal.result("Creator module opened.");
}

function closeCreatorPanel() {
    if (!DOM.creatorPanel) return;

    DOM.creatorPanel.classList.remove("open");
}

function createShareText() {
    const title =
        App.selectedEntry
            ? App.selectedEntry.title
            : DOM.creatorResultTitle.textContent;

    const confidence =
        DOM.creatorConfidence
            ? DOM.creatorConfidence.textContent
            : "--.--%";

    return [
        "A.R.C.S. RESULT",
        "",
        `TARGET LOCK：${title}`,
        `AI CONFIDENCE：${confidence}`,
        "",
        "Generated by A.R.C.S.",
        "#ProjectSHIZ #ARCS #CreatorEdition"
    ].join("\n");
}

function shareToX() {
    const text = createShareText();

    copyShareText(text);

    const url =
        "https://twitter.com/intent/tweet?text=" +
        encodeURIComponent(text);

    window.open(url, "_blank", "noopener,noreferrer");

    Terminal.result("Share text copied. Attach saved PNG on X.");
    setSystemMessage("SHARE READY");
}

async function copyShareText(text) {
    try {
        await navigator.clipboard.writeText(text);
        Terminal.result("Share text copied to clipboard.");
    } catch {
        Terminal.warn("Clipboard copy failed.");
    }
}

async function saveResultPng() {
    if (!DOM.creatorCard) {
        Terminal.warn("Creator card not found.");
        return;
    }

    if (typeof html2canvas === "undefined") {
        Terminal.warn("PNG module is not loaded.");
        setSystemMessage("PNG MODULE ERROR");
        return;
    }

    Terminal.system("PNG capture started.");
    setSystemMessage("PNG CAPTURE");

    try {
        const canvas = await html2canvas(DOM.creatorCard, {
            backgroundColor: null,
            scale: 3,
            useCORS: true
        });

        const link = document.createElement("a");
        link.download = createPngFileName();
        link.href = canvas.toDataURL("image/png");
        link.click();

        Terminal.system("PNG saved.");
        setSystemMessage("PNG SAVED");
    } catch {
        Terminal.warn("PNG capture failed.");
        setSystemMessage("PNG ERROR");
    }
}


/*==================================================
    STATUS CLASS
==================================================*/

function getStatusClass(status) {
    switch (status) {
        case "CHECKING":
            return "is-checking";

        case "SCANNING":
            return "is-scanning";

        case "TARGET LOCK":
            return "is-locked";

        default:
            return "";
    }
}


/*==================================================
    UI CONTROL
==================================================*/

function setSystemMessage(message) {
    DOM.systemMessage.textContent = message;
}

function setAppState(state) {
    App.state = state;
    document.body.dataset.state = state;
}

function setRingMode(mode) {
    DOM.ring.classList.remove(
        "ring-idle",
        "ring-boot",
        "ring-scan",
        "ring-lock"
    );

    DOM.ring.classList.add(`ring-${mode}`);
}

function setAllEntryStatus(status) {
    App.entries.forEach(entry => {
        entry.status = status;
    });

    renderEntryCards();
}

function setEntryStatus(id, status) {
    const entry = App.entries.find(item => item.id === id);

    if (!entry) return;

    entry.status = status;

    renderEntryCards();
}

function resetEntryStatus() {
    App.entries.forEach(entry => {
        entry.status = "READY";
    });

    renderEntryCards();
}

function resetResultPanel() {
    DOM.resultTitle.textContent = "---";
    resetTitleFit(DOM.resultTitle);

    DOM.resultId.textContent = "----";
    DOM.resultConfidence.textContent = "--.--%";
    DOM.resultStatus.textContent = "LOCKED";
}

function resetSystem() {
    if (App.isRunning) return;

    App.selectedEntry = null;
    App.selectedIndex = -1;

    resetEntryStatus();
    resetResultPanel();
    resetCreatorCard();
    closeCreatorPanel();

    setAppState("READY");
    setRingMode("idle");
    setSystemMessage("SYSTEM READY");

    Terminal.system("Operation reset.");
}


/*==================================================
    CINEMATIC SCENES
==================================================*/

const Scene = {
    async boot() {
        setAppState("BOOT");
        setRingMode("boot");

        Sound.play("boot");

        Terminal.system(`${SYSTEM.project}`);
        Terminal.system(`Launching ${SYSTEM.name}...`);
        Terminal.system(`${SYSTEM.fullName}`);
        Terminal.system(`Version ${SYSTEM.version}`);

        await sceneStep("POWER CORE", "Power Core..............OK", "system", 310);
        await sceneStep("HUD LINK", "HUD Interface..........OK", "system", 310);
        await sceneStep("A.R.C.S. CORE", "A.R.C.S. Core..........ONLINE", "system", 360);
        await sceneStep("TARGET ENGINE", "Target Engine..........STANDBY", "system", 360);
        await sceneStep("A.R.C.S. ONLINE", "A.R.C.S. online.", "system", 520);
    },

    async auth() {
        setAppState("AUTH");

        Sound.play("auth");

        Terminal.auth("Operator verification started.");

        await sceneStep(
            "AUTHENTICATING",
            "Operator signature.....SCANNING",
            "auth",
            480
        );

        await sceneStep(
            App.settings.operatorName,
            `Operator...............${App.settings.operatorName}`,
            "auth",
            620
        );

        await sceneStep(
            "SIGNATURE MATCH",
            "Signature..............MATCH",
            "auth",
            420
        );

        await sceneStep(
            "ACCESS GRANTED",
            "Access level...........GRANTED",
            "auth",
            520
        );

        await sceneStep(
            "WELCOME",
            `Welcome, ${App.settings.operatorName}.`,
            "auth",
            420
        );
    },

    async database() {
        setAppState("DATABASE");

        Sound.play("database");

        Terminal.database("Archive link established.");

        await sceneStep(
            "DATABASE LINK",
            "Archive connection.....OK",
            "database",
            420
        );

        await sceneStep(
            "VERIFYING",
            `Registered Entries.....${App.entries.length}`,
            "database",
            420
        );

        await sceneStep(
            "RECORD CHECK",
            "Record integrity.......RUNNING",
            "database",
            300
        );

        await checkCards();

        await sceneStep(
            "DATABASE READY",
            "Record integrity.......OK",
            "database",
            560
        );
    },

    async scan() {
        setAppState("SCAN");
        setRingMode("scan");

        Sound.play("scan_loop");

        setAllEntryStatus("SCANNING");

        Terminal.ai("Selection engine activated.");
        Terminal.ai("Candidate analysis started.");

        const sequence = [
            "PATTERN MATCH",
            "TRACE DATA",
            "BALANCE CHECK",
            "RANDOM SEED",
            "TARGET SEARCH",
            "DECISION PATH"
        ];

        const logs = [
            "Pattern matching........RUNNING",
            "Trace analysis..........RUNNING",
            "Balance check...........CALCULATING",
            "Random seed.............GENERATED",
            "Candidate matrix........ACTIVE",
            "Decision path...........LOCKING"
        ];

        const steps = 62;

        for (let i = 0; i < steps; i++) {
            if (i % 13 === 0) {
                const entry = randomEntry();
                setSystemMessage(entry.title);
            } else {
                setSystemMessage(sequence[i % sequence.length]);
            }

            if (i % 12 === 0 && logs[Math.floor(i / 12)]) {
                Terminal.ai(logs[Math.floor(i / 12)]);
            }

            await sleep(26 + i * 2);
        }

        App.selectedIndex = randomIndex();
        App.selectedEntry = App.entries[App.selectedIndex];

        Terminal.ai("Candidate selected.");

        await sleep(300);
    },

    async lock() {
        setAppState("LOCK");
        setRingMode("lock");

        Sound.stop("scan_loop");
        Sound.play("lock");

        setAllEntryStatus("READY");
        setEntryStatus(App.selectedEntry.id, "TARGET LOCK");

        Terminal.lock("Target signature detected.");

        await sceneStep(
            "TARGET FOUND",
            "Target signature........FOUND",
            "lock",
            320
        );

        await sceneStep(
            "IDENTIFYING",
            `Database ID.............${formatId(App.selectedIndex)}`,
            "lock",
            320
        );

        await sceneStep(
            "LOCK COMPLETE",
            `Target locked : ${App.selectedEntry.title}`,
            "lock",
            620
        );
    },

    async result() {
        setAppState("RESULT");

        Sound.play("result");

        const idText = formatId(App.selectedIndex);
        const confidence = createConfidence();

        DOM.resultId.textContent = idText;
        DOM.resultConfidence.textContent = `${confidence}%`;
        DOM.resultStatus.textContent = "LOCKED";

        updateCreatorCard(
            App.selectedEntry,
            idText,
            confidence
        );

        Terminal.result("Operation result received.");
        Terminal.result(`Selected target : ${App.selectedEntry.title}`);
        Terminal.result(`Database ID : ${idText}`);
        Terminal.result(`AI Confidence : ${confidence}%`);

        await revealResultTitle(App.selectedEntry.title);

        Terminal.result("Creator result card ready.");
        Terminal.result("Selection complete.");
    }
};


/*==================================================
    SCENE HELPERS
==================================================*/

async function sceneStep(display, logMessage, logType, wait) {
    setSystemMessage(display);

    if (logMessage) {
        writeSceneLog(logMessage, logType);
    }

    await sleep(wait);
}

function writeSceneLog(message, type) {
    switch (type) {
        case "auth":
            Terminal.auth(message);
            break;

        case "database":
            Terminal.database(message);
            break;

        case "ai":
            Terminal.ai(message);
            break;

        case "lock":
            Terminal.lock(message);
            break;

        case "result":
            Terminal.result(message);
            break;

        default:
            Terminal.system(message);
            break;
    }
}


/*==================================================
    ENGINE
==================================================*/

const Engine = {
    async start() {
        if (App.isRunning) return;

        if (App.entries.length === 0) {
            Terminal.warn("No entry data found.");
            setSystemMessage("NO DATA");
            Sound.play("error");
            return;
        }

        App.isRunning = true;

        DOM.startButton.disabled = true;
        DOM.resetButton.disabled = true;

        resetResultPanel();
        resetCreatorCard();
        closeCreatorPanel();

        try {
            await Scene.boot();
            await Scene.auth();
            await Scene.database();
            await Scene.scan();
            await Scene.lock();
            await Scene.result();
        } finally {
            App.isRunning = false;

            DOM.startButton.disabled = false;
            DOM.resetButton.disabled = false;
        }
    }
};


/*==================================================
    CARD CHECK
==================================================*/

async function checkCards() {
    for (const entry of App.entries) {
        setEntryStatus(entry.id, "CHECKING");
        await sleep(42);
    }

    await sleep(220);

    setAllEntryStatus("READY");
}


/*==================================================
    RESULT TITLE REVEAL
==================================================*/

async function revealResultTitle(title) {
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789■□◇◆▓▒░";
    const finalText = title;

    DOM.resultTitle.textContent = finalText;

    fitResultTitle(DOM.resultTitle, {
        maxSize: 60,
        minSize: 22,
        maxLines: 4
    });

    for (let i = 0; i < finalText.length; i++) {
        for (let j = 0; j < 3; j++) {
            const display =
                finalText.slice(0, i) +
                chars[Math.floor(Math.random() * chars.length)] +
                "□".repeat(Math.max(finalText.length - i - 1, 0));

            DOM.resultTitle.textContent = display;

            await sleep(28);
        }

        DOM.resultTitle.textContent =
            finalText.slice(0, i + 1) +
            "□".repeat(Math.max(finalText.length - i - 1, 0));

        await sleep(32);
    }

    DOM.resultTitle.textContent = finalText;
}


/*==================================================
    BOOT SCREEN
==================================================*/

function closeBootScreen() {
    if (!DOM.bootScreen) return;

    setTimeout(() => {
        DOM.bootScreen.classList.add("is-hidden");
        Terminal.system("Boot screen closed.");
    }, 2300);
}


/*==================================================
    EVENTS
==================================================*/

DOM.addEntryButton.addEventListener("click", addEntry);

DOM.clearAllButton.addEventListener("click", clearAllEntries);

DOM.clearLogButton.addEventListener("click", () => {
    Terminal.clear();
});

DOM.entryInput.addEventListener("keydown", event => {
    if (event.key === "Enter") {
        addEntry();
    }
});

DOM.startButton.addEventListener("click", () => {
    Engine.start();
});

DOM.resetButton.addEventListener("click", resetSystem);

DOM.settingsButton.addEventListener("click", openSettings);

DOM.closeSettingsButton.addEventListener("click", closeSettings);

DOM.saveOperatorButton.addEventListener("click", saveOperatorName);

DOM.operatorInput.addEventListener("keydown", event => {
    if (event.key === "Enter") {
        saveOperatorName();
    }
});

DOM.settingsPanel.addEventListener("click", event => {
    if (event.target === DOM.settingsPanel) {
        closeSettings();
    }
});

DOM.openCreatorButton.addEventListener("click", openCreatorPanel);

DOM.closeCreatorButton.addEventListener("click", closeCreatorPanel);

DOM.shareXButton.addEventListener("click", shareToX);

DOM.saveResultButton.addEventListener("click", saveResultPng);

DOM.creatorPanel.addEventListener("click", event => {
    if (event.target === DOM.creatorPanel) {
        closeCreatorPanel();
    }
});


/*==================================================
    INIT
==================================================*/

function init() {
    setAppState("READY");

    setRingMode("idle");

    resetResultPanel();
    resetCreatorCard();

    Terminal.system(`${SYSTEM.project} interface online.`);
    Terminal.system(`${SYSTEM.name} standby.`);

    loadSettings();

    renderSettings();

    loadEntries();

    render();

    Terminal.system("System ready.");

    closeBootScreen();
}

init();
