"use strict";

/*==================================================
    CREATOR CARD
==================================================*/

function updateCreatorCard(entry, idText, confidence) {
    if (!DOM.creatorPanel) return;

    DOM.creatorResultTitle.textContent = entry.title;

    fitResultTitle(DOM.creatorResultTitle, {
        maxSize: 56,
        minSize: 24,
        maxLines: 3
    });

    DOM.creatorOperator.textContent = App.settings.operatorName;
    DOM.creatorResultId.textContent = idText;
    DOM.creatorConfidence.textContent = `${confidence}%`;
}

function resetCreatorCard() {
    if (!DOM.creatorPanel) return;

    DOM.creatorResultTitle.textContent = "---";
    resetTitleFit(DOM.creatorResultTitle);

    DOM.creatorOperator.textContent = "---";
    DOM.creatorResultId.textContent = "----";
    DOM.creatorConfidence.textContent = "--.--%";
}

async function openCreatorPanel() {
    if (!DOM.creatorPanel) return;

    if (!App.selectedEntry) {
        Terminal.warn("No result data available.");
        setSystemMessage("NO RESULT");
        return;
    }

    Terminal.system("Accessing creator module...");
    setSystemMessage("CREATOR MODULE");

    await sleep(260);

    DOM.creatorPanel.classList.add("open");

    Terminal.result("Creator module opened.");
}

function closeCreatorPanel() {
    if (!DOM.creatorPanel) return;

    DOM.creatorPanel.classList.remove("open");
}

function createShareText() {
    const title =
        App.selectedEntry
            ? App.selectedEntry.title
            : DOM.creatorResultTitle.textContent;

    const confidence =
        DOM.creatorConfidence
            ? DOM.creatorConfidence.textContent
            : "--.--%";

    return [
        "A.R.C.S. RESULT",
        "",
        `TARGET LOCK：${title}`,
        `AI CONFIDENCE：${confidence}`,
        "",
        "Generated by A.R.C.S.",
        "#ProjectSHIZ #ARCS #CreatorEdition"
    ].join("\n");
}

function shareToX() {
    const text = createShareText();

    copyShareText(text);

    const url =
        "https://twitter.com/intent/tweet?text=" +
        encodeURIComponent(text);

    window.open(url, "_blank", "noopener,noreferrer");

    Terminal.result("Share text copied. Attach saved PNG on X.");
    setSystemMessage("SHARE READY");
}

async function copyShareText(text) {
    try {
        await navigator.clipboard.writeText(text);
        Terminal.result("Share text copied to clipboard.");
    } catch {
        Terminal.warn("Clipboard copy failed.");
    }
}

async function saveResultPng() {
    if (!DOM.creatorCard) {
        Terminal.warn("Creator card not found.");
        return;
    }

    if (typeof html2canvas === "undefined") {
        Terminal.warn("PNG module is not loaded.");
        setSystemMessage("PNG MODULE ERROR");
        return;
    }

    Terminal.system("PNG capture started.");
    setSystemMessage("PNG CAPTURE");

    try {
        const canvas = await html2canvas(DOM.creatorCard, {
            backgroundColor: null,
            scale: 3,
            useCORS: true
        });

        const link = document.createElement("a");
        link.download = createPngFileName();
        link.href = canvas.toDataURL("image/png");
        link.click();

        Terminal.system("PNG saved.");
        setSystemMessage("PNG SAVED");
    } catch {
        Terminal.warn("PNG capture failed.");
        setSystemMessage("PNG ERROR");
    }
}

